source 'https://rubygems.org'

gem 'acts-as-taggable-on'
gem 'acts_as_votable', '~> 0.10.0'
gem 'ambry'
gem 'annotate_gem'
gem 'authority'
gem 'auto_html'
gem 'autoprefixer-rails'
gem 'autosize'
gem 'bh'
gem 'bootstrap-sass'
gem 'carrierwave-aws'
gem 'clockwork'
gem 'cocoon'
gem 'codemirror-rails'
gem 'coffee-rails'
gem 'daemons'
gem 'delayed_job_active_record'
gem 'delayed_job_web'
gem 'devise'
gem 'excon', '~> 0.39.5'
gem 'figaro'
gem 'font-awesome-sass'
gem 'friendly_id'
gem 'gibbon'
gem 'google-code-prettify-rails'
gem 'gravatar-ultimate'
gem 'impressionist'
gem 'jbuilder'
gem 'jquery-minicolors-rails'
gem 'jquery-rails'
gem 'jquery-tokeninput-rails'
gem 'jquery-turbolinks'
gem 'jquery-ui-rails'
gem 'mailgun'
gem 'markdown-rails'
gem 'meetup_client'
gem 'merit'
gem 'meta-tags', '~> 2.0.0'
gem 'mini_magick'
gem 'multi_json', '~> 1.10.1'
gem 'mysql2', '0.4.10', group: :production
gem 'oj', '~> 2.10.2'
gem 'pagedown-bootstrap-rails', github: 'rorlab/pagedown-bootstrap-rails'
gem 'pageless-rails', github: 'rorlab/pageless-rails'
gem 'placeholdit'
gem 'puma'
gem 'rails', '4.2.10'
gem 'rails_12factor', group: :production
gem 'recaptcha', require: 'recaptcha/rails'
gem 'redcarpet'
gem 'remotipart', '~> 1.2'
gem 'rolify'
gem 'sanitize'
gem 'sass-rails'
gem 'sdoc', group: :doc
gem 'search_cop'
gem 'simple_enum', '~> 2.0.0'
gem 'simple_form'
gem 'sqlite3', group: :development
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'validate_url'
gem 'webshots', github: 'rorlab/webshots'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'yaml_db'

group :development do
  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'capistrano', '~> 3.10.1'
  gem 'capistrano-bundler'
  gem 'capistrano-figaro-yml'
  gem 'capistrano-rails'
  gem 'capistrano-rails-console'
  gem 'capistrano-rails-tail-log'
  gem 'capistrano-rbenv'
  gem 'capistrano-rbenv-install'
  gem 'capistrano-upload-config'
  gem 'capistrano3-nginx', '~> 2.1.6'
  gem 'capistrano3-puma'
  gem 'rails-erd'
  gem 'terminal-notifier-guard'
end

group :development, :test do
  gem 'factory_girl_rails', '~> 4.2.1'
  gem 'guard', '~> 2'
  gem 'guard-rspec', require: false
  gem 'letter_opener'
  gem 'rspec-rails', '~> 2.14.0'
  gem 'spring'
  gem 'spring-commands-rspec'
end

group :test do
  gem 'capybara', '~> 2.1.0'
  gem 'capybara-webkit'
  gem 'database_cleaner', '~> 1.0.1'
  gem 'faker', '~> 1.1.2'
  gem 'launchy', '~> 2.4.2'
  gem 'selenium-webdriver', '~> 2.35.1'
  gem 'shoulda-matchers', require: false
  gem 'simplecov', :require => false
  gem 'vcr', '2.9.3'
  gem 'webmock', '1.19.0'
end
