# == Schema Information
#
# Table name: favlinks
#
#  id               :integer          not null, primary key
#  title            :string(255)      not null
#  description      :text(65535)
#  linkurl          :string(255)      not null
#  writer_id        :integer
#  shared           :boolean          default(TRUE)
#  bundlelink_id    :integer
#  created_at       :datetime
#  updated_at       :datetime
#  capture_loc      :string(255)
#  with_screen_shot :boolean          default(TRUE)
#

require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FavlinksController do

  before :each do
    @current_user = User.create!                      \
                         email:"user1@email.com",    \
                         password:"12345678",         \
                         confirmed_at: Time.now

    @bulletin = create(:bulletin)
  end

  # This should return the minimal set of attributes required to create a valid
  # Favlink. As you add validations to Favlink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { attributes_for(:favlink) }
  let(:invalid_attributes) { attributes_for(:favlink, linkurl: nil) }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FavlinksController. Be sure to keep this updated too.
  let(:valid_session) do
    @current_user.confirm!
    sign_in @current_user
  end

  describe "GET index" do
    it "assigns all favlinks as @favlinks" do
      favlink = @current_user.favlinks.create! valid_attributes
      get :index, {}, valid_session
      assigns(:favlinks).should eq([favlink])
    end
  end

  describe "GET show" do
    it "assigns the requested favlink as @favlink" do
      favlink = @current_user.favlinks.create! valid_attributes
      get :show, {:id => favlink.to_param}, valid_session
      assigns(:favlink).should eq(favlink)
    end
  end

  describe "GET new" do
    it "assigns a new favlink as @favlink" do
      get :new, {}, valid_session
      assigns(:favlink).should be_a_new(Favlink)
    end
  end

  describe "GET edit" do
    it "assigns the requested favlink as @favlink" do
      favlink = @current_user.favlinks.create! valid_attributes
      get :edit, {:id => favlink.to_param}, valid_session
      assigns(:favlink).should eq(favlink)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Favlink" do
        expect {
          post :create, {:favlink => valid_attributes}, valid_session
        }.to change(Favlink, :count).by(1)
      end

      it "assigns a newly created favlink as @favlink" do
        post :create, {:favlink => valid_attributes}, valid_session
        assigns(:favlink).should be_a(Favlink)
        assigns(:favlink).should be_persisted
      end

      it "redirects to the created favlink" do
        post :create, {:favlink => valid_attributes}, valid_session
        response.should redirect_to(Favlink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved favlink as @favlink" do
        # Trigger the behavior that occurs when invalid params are submitted
        Favlink.any_instance.stub(:save).and_return(false)
        post :create, {:favlink => valid_attributes }, valid_session
        assigns(:favlink).should be_a_new(Favlink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Favlink.any_instance.stub(:save).and_return(false)
        post :create, {:favlink => valid_attributes}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested favlink" do
        favlink = @current_user.favlinks.create! valid_attributes
        # Assuming there are no other favlinks in the database, this
        # specifies that the Favlink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Favlink.any_instance.should_receive(:update).with({ "linkurl" => "http://google.com" })
        put :update, {:id => favlink.to_param, :favlink => { "linkurl" => "http://google.com" }}, valid_session
      end

      it "assigns the requested favlink as @favlink" do
        favlink = @current_user.favlinks.create! valid_attributes
        put :update, {:id => favlink.to_param, :favlink => valid_attributes}, valid_session
        assigns(:favlink).should eq(favlink)
      end

      it "redirects to the favlink" do
        favlink = @current_user.favlinks.create! valid_attributes
        put :update, {:id => favlink.to_param, :favlink => valid_attributes}, valid_session
        response.should redirect_to(favlink)
      end
    end

    describe "with invalid params" do
      it "assigns the favlink as @favlink" do
        favlink = @current_user.favlinks.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Favlink.any_instance.stub(:save).and_return(false)
        put :update, {:id => favlink.to_param, :favlink => invalid_attributes}, valid_session
        assigns(:favlink).should eq(favlink)
      end

      it "re-renders the 'edit' template" do
        favlink = @current_user.favlinks.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Favlink.any_instance.stub(:save).and_return(false)
        put :update, {:id => favlink.to_param, :favlink => invalid_attributes}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested favlink" do
      favlink = @current_user.favlinks.create! valid_attributes
      expect {
        delete :destroy, {:id => favlink.to_param}, valid_session
      }.to change(Favlink, :count).by(-1)
    end

    it "redirects to the favlinks list" do
      favlink = @current_user.favlinks.create! valid_attributes
      delete :destroy, {:id => favlink.to_param}, valid_session
      response.should redirect_to(favlinks_url)
    end
  end

end
