# == Schema Information
#
# Table name: plazas
#
#  id              :integer          not null, primary key
#  postitable_id   :integer
#  postitable_type :string(255)
#  visible         :boolean
#  created_at      :datetime
#  updated_at      :datetime
#

require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlazasController do

  # This should return the minimal set of attributes required to create a valid
  # Plaza. As you add validations to Plaza, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlazasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all plazas as @plazas" do
      plaza = Plaza.create! valid_attributes
      get :index, {}, valid_session
      assigns(:plazas).should eq([plaza])
    end
  end

  describe "GET show" do
    it "assigns the requested plaza as @plaza" do
      plaza = Plaza.create! valid_attributes
      get :show, {:id => plaza.to_param}, valid_session
      assigns(:plaza).should eq(plaza)
    end
  end

  describe "GET new" do
    it "assigns a new plaza as @plaza" do
      get :new, {}, valid_session
      assigns(:plaza).should be_a_new(Plaza)
    end
  end

  describe "GET edit" do
    it "assigns the requested plaza as @plaza" do
      plaza = Plaza.create! valid_attributes
      get :edit, {:id => plaza.to_param}, valid_session
      assigns(:plaza).should eq(plaza)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Plaza" do
        expect {
          post :create, {:plaza => valid_attributes}, valid_session
        }.to change(Plaza, :count).by(1)
      end

      it "assigns a newly created plaza as @plaza" do
        post :create, {:plaza => valid_attributes}, valid_session
        assigns(:plaza).should be_a(Plaza)
        assigns(:plaza).should be_persisted
      end

      it "redirects to the created plaza" do
        post :create, {:plaza => valid_attributes}, valid_session
        response.should redirect_to(Plaza.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved plaza as @plaza" do
        # Trigger the behavior that occurs when invalid params are submitted
        Plaza.any_instance.stub(:save).and_return(false)
        post :create, {:plaza => {  }}, valid_session
        assigns(:plaza).should be_a_new(Plaza)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Plaza.any_instance.stub(:save).and_return(false)
        post :create, {:plaza => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested plaza" do
        plaza = Plaza.create! valid_attributes
        # Assuming there are no other plazas in the database, this
        # specifies that the Plaza created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Plaza.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => plaza.to_param, :plaza => { "these" => "params" }}, valid_session
      end

      it "assigns the requested plaza as @plaza" do
        plaza = Plaza.create! valid_attributes
        put :update, {:id => plaza.to_param, :plaza => valid_attributes}, valid_session
        assigns(:plaza).should eq(plaza)
      end

      it "redirects to the plaza" do
        plaza = Plaza.create! valid_attributes
        put :update, {:id => plaza.to_param, :plaza => valid_attributes}, valid_session
        response.should redirect_to(plaza)
      end
    end

    describe "with invalid params" do
      it "assigns the plaza as @plaza" do
        plaza = Plaza.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Plaza.any_instance.stub(:save).and_return(false)
        put :update, {:id => plaza.to_param, :plaza => {  }}, valid_session
        assigns(:plaza).should eq(plaza)
      end

      it "re-renders the 'edit' template" do
        plaza = Plaza.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Plaza.any_instance.stub(:save).and_return(false)
        put :update, {:id => plaza.to_param, :plaza => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested plaza" do
      plaza = Plaza.create! valid_attributes
      expect {
        delete :destroy, {:id => plaza.to_param}, valid_session
      }.to change(Plaza, :count).by(-1)
    end

    it "redirects to the plazas list" do
      plaza = Plaza.create! valid_attributes
      delete :destroy, {:id => plaza.to_param}, valid_session
      response.should redirect_to(plazas_url)
    end
  end

end
