require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RblogsController do

  # This should return the minimal set of attributes required to create a valid
  # Rblog. As you add validations to Rblog, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RblogsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all rblogs as @rblogs" do
      rblog = Rblog.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rblogs).should eq([rblog])
    end
  end

  describe "GET show" do
    it "assigns the requested rblog as @rblog" do
      rblog = Rblog.create! valid_attributes
      get :show, {:id => rblog.to_param}, valid_session
      assigns(:rblog).should eq(rblog)
    end
  end

  describe "GET new" do
    it "assigns a new rblog as @rblog" do
      get :new, {}, valid_session
      assigns(:rblog).should be_a_new(Rblog)
    end
  end

  describe "GET edit" do
    it "assigns the requested rblog as @rblog" do
      rblog = Rblog.create! valid_attributes
      get :edit, {:id => rblog.to_param}, valid_session
      assigns(:rblog).should eq(rblog)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Rblog" do
        expect {
          post :create, {:rblog => valid_attributes}, valid_session
        }.to change(Rblog, :count).by(1)
      end

      it "assigns a newly created rblog as @rblog" do
        post :create, {:rblog => valid_attributes}, valid_session
        assigns(:rblog).should be_a(Rblog)
        assigns(:rblog).should be_persisted
      end

      it "redirects to the created rblog" do
        post :create, {:rblog => valid_attributes}, valid_session
        response.should redirect_to(Rblog.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rblog as @rblog" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rblog.any_instance.stub(:save).and_return(false)
        post :create, {:rblog => { "title" => "invalid value" }}, valid_session
        assigns(:rblog).should be_a_new(Rblog)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rblog.any_instance.stub(:save).and_return(false)
        post :create, {:rblog => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rblog" do
        rblog = Rblog.create! valid_attributes
        # Assuming there are no other rblogs in the database, this
        # specifies that the Rblog created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Rblog.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => rblog.to_param, :rblog => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested rblog as @rblog" do
        rblog = Rblog.create! valid_attributes
        put :update, {:id => rblog.to_param, :rblog => valid_attributes}, valid_session
        assigns(:rblog).should eq(rblog)
      end

      it "redirects to the rblog" do
        rblog = Rblog.create! valid_attributes
        put :update, {:id => rblog.to_param, :rblog => valid_attributes}, valid_session
        response.should redirect_to(rblog)
      end
    end

    describe "with invalid params" do
      it "assigns the rblog as @rblog" do
        rblog = Rblog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rblog.any_instance.stub(:save).and_return(false)
        put :update, {:id => rblog.to_param, :rblog => { "title" => "invalid value" }}, valid_session
        assigns(:rblog).should eq(rblog)
      end

      it "re-renders the 'edit' template" do
        rblog = Rblog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rblog.any_instance.stub(:save).and_return(false)
        put :update, {:id => rblog.to_param, :rblog => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rblog" do
      rblog = Rblog.create! valid_attributes
      expect {
        delete :destroy, {:id => rblog.to_param}, valid_session
      }.to change(Rblog, :count).by(-1)
    end

    it "redirects to the rblogs list" do
      rblog = Rblog.create! valid_attributes
      delete :destroy, {:id => rblog.to_param}, valid_session
      response.should redirect_to(rblogs_url)
    end
  end

end
